### ISSUE TITLE
Extract information

### ISSUE THREAD

**Issue by Viet1004** [Viet1004/Code4Earth-2024-Challenge-24#10]
Extract texts, images, tables

**Comment by thinhngo-x** [comment]
@haiyenvu96 @Viet1004 any progress?

**Comment by Viet1004** [comment]
Not yet. But will try st tonight

**Comment by thinhngo-x** [comment]
Some issues:

- Mapping tables to their captions.

**Comment by thinhngo-x** [comment]
Langchain has some good APIs for this, take a look: https://python.langchain.com/v0.1/docs/modules/data_connection/document_loaders/pdf/
