### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by thinhngo-x** [Viet1004/Code4Earth-2024-Challenge-24#3]
Study KG visualization methods: data types, frameworks, ...

**Comment by thinhngo-x** [comment]
What I expect for now:
- A function that takes in a KG and opens a console to visualize the KG interactive.
- You can refer to this JSON file https://github.com/Viet1004/Code4Earth-2024-Challenge-24/blob/e5e897ab98f57261052c7a88edce44de7b670153/assets/toy_kg_cleaned.json for the input format.
- Neo4j has a standalone product to visualize KGs https://neo4j.com/blog/neo4j-bloom-everywhere-this-spring/

**Comment by HoangAnhP** [comment]
@thinhngo-x By "opens a console to visualize the KG interactive" do you mean something like this ?
https://www.youtube.com/watch?v=Z42VVH9qngo&t=59s

**Comment by thinhngo-x** [comment]
In the link is a demo of a Neo4J app. I doubt that it is a simple Python app but a server with a complete backend and frontend. What I expect here is much simpler, just like when you use matplotlib to plot charts, the Python script (not the notebook) will open a *console* to visualize the charts. So I'd like a console like this but to visualize an *interactive* graph.

Take a look at these libs, https://pyviz.org/tools.html#graphs-and-networks

**Comment by thinhngo-x** [comment]
Or else, you could implement a notebook, not necessarily a Python script.

Like this: https://github.com/WestHealth/pyvis?tab=readme-ov-file
